package cli

// TokenUsage captures the size of a single LLM call's prompt and
// response, in tokens. Populated by each invoker from the vendor
// CLI's structured output (claude/gemini JSON mode) or stdout
// metadata (codex).
//
// **These are prompt/response *size* numbers, not billing numbers.**
// For Anthropic specifically, InputTokens includes prompt-cache reads
// and creation tokens — Anthropic discounts cache reads to ~10% of
// list price, so summing InputTokens across calls does not give
// dollars-spent (and nor does Total()). The numbers exist so users
// can answer "how big was the prompt I sent?" / "how big was the
// reply?" — the kind of question relevant when scoping a review or
// estimating context-window pressure. For exact spend, check the
// vendor's own billing dashboard. See parseClaudeJSON in parsers.go
// for the v0.7.1 rationale (pre-fix InputTokens excluded cache reads
// to be cost-shaped, and the displayed "in" collapsed to single
// digits on cached prompts which read as a broken parser).
//
// Zero values mean "we couldn't determine usage from this call" —
// the CLI version may not support a structured-output flag, or its
// output shape didn't match what we expected. Callers should treat
// `usage.IsZero()` as "unknown" rather than "no tokens used."
type TokenUsage struct {
	// InputTokens is the size of the prompt sent to the model
	// (system prompt + diff + any wrapper text). Anthropic calls
	// the components `input_tokens` + `cache_read_input_tokens` +
	// `cache_creation_input_tokens`; we sum all three since they
	// all represent prompt content the user wrote. Google calls
	// it `promptTokenCount`; OpenAI calls it `prompt_tokens`.
	// All three vendor names normalise to this single field.
	InputTokens int

	// OutputTokens is the size of the response generated by the
	// model. Anthropic: `output_tokens`. Google: `candidatesTokenCount`.
	// OpenAI: `completion_tokens`.
	OutputTokens int

	// TotalOnly indicates the source CLI reported a single combined
	// total without an input/output split. Codex's pre-v0.128
	// stdout metadata is the canonical example ("tokens used: N").
	// When set, the total is in InputTokens (we fold it there
	// instead of inventing a 50/50 split) and display callers
	// should render as "Nk total" rather than "Nk in / 0 out" —
	// the latter would mislead users into thinking the model
	// produced no output. Tools that aggregate across calls should
	// still use Total() for the running sum.
	TotalOnly bool
}

// IsZero reports whether neither token count was populated. The
// caller uses this to decide between "show '12.3k in / 4.5k out'"
// and "omit the token suffix entirely" on the per-LLM completion
// line — printing "0 in / 0 out" would mislead users into thinking
// the call was free when actually we just didn't know.
func (u TokenUsage) IsZero() bool {
	return u.InputTokens == 0 && u.OutputTokens == 0
}

// Total is the sum of input + output, useful for closing-line
// summaries that show overall token volume across all agents. For
// TotalOnly usage, InputTokens already holds the full total so the
// math still works — OutputTokens is 0 by definition there.
//
// Like the underlying fields, this is a *size* aggregate, not a
// dollar/spend aggregate. For Anthropic specifically, the sum
// over-states billed amount because cache-read tokens are
// discounted ~10×. See the TokenUsage struct doc above for why
// we picked size over spend.
func (u TokenUsage) Total() int {
	return u.InputTokens + u.OutputTokens
}
